name: GitHub Actions Maven Test
on:
  push:
    branches:
      - dev
    pull_request:
     - dev
jobs: 
  Test-Application:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'amazoncorretto'
      - name: Maven Test
        run: mvn --batch-mode --update-snapshots verify
