name: GitHub Actions Maven Test
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs: 
  Test-Application:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven Test
        run: mvn --batch-mode --update-snapshots verify
